[package]
name = "mytrie"
description = "Trie implmentation"
version = "0.2.1"
edition = "2021"
license = "WTFPL"
documentation = "https://docs.rs/mytrie/latest/mytrie/struct.Trie.html"
homepage = "https://github.com/UgnilJoZ/mytrie"

[dependencies]

[dev-dependencies]
rand = "0.8.5"